### ISSUE TITLE
Resource creation stopped working

### ISSUE THREAD

**Issue by niekdemelker** [Tools4everBV/HelloID-Conn-Prov-Target-MijnCaress#1]
sinds a week or 3 the resource creation stopped working. there seems to be an error on the collection of userdata.

on line 22, `$users = $caressService.GetUsers()` throws an exeption: Exception calling "GetUsers" with "0" argument(s): "An invalid character was found in text content.

the session to the service is created, so authentication should be fine, Is there a change in the API specs?

**Comment by Rick-Jongbloed** [comment]
@niekdemelker , is this still an issue or has this issue been resolved?

**Comment by JeroenBL** [comment]
This issue has been open for quite some time without any recent activity. We appreciate all the feedback and contributions.

To keep our issue tracker focused and organized, we are closing this issue. If the problem persists or if there are any new developments, please feel free to reopen the issue or create a new one.

Thank you for your understanding and continued support!
